services:
  backend:
    build:
      context: ./BackEnd
    container_name: meu_backend_local
    env_file:
      - .env
    ports:
      - "8080:8080"
    volumes:
      - ./BackEnd:/app
    restart: unless-stopped

  frontend:
    build:
      context: ./FrontEnd
    container_name: meu_frontend_local
    ports:
      - "80:80"
    depends_on:
      - backend
    volumes:
      - ./FrontEnd:/usr/share/nginx/html
    restart: unless-stopped
